name: size-limit

on: push

jobs:
  size-limit:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run size-limit
        run: yarn size
